server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eod_parallelism_database
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: eod-parallelism
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      execution-process-topic: execution-process-topic
      execution-entity-topic: execution-entity-topic
    producer:
      transaction-id-prefix: transactional-producer-id
    consumer:
      group-id: eod-parallelism-group
      properties:
        allow.auto.create.topics: false
      auto-offset-reset: earliest

logging:
  level:
    org:
      apache:
        kafka: OFF